### ISSUE TITLE
RTD build for the project is broken

### ISSUE THREAD

**Issue by pradyunsg** [pypa/pyproject-hooks#179]
This is due to:

> Problem in your project's configuration. Invalid configuration option "build.os": build not found

**Comment by NormanDunbar** [comment]
Evening All,

is there anything I need to do to avoid this error? I've jusProblem in your project's configuration. Invalid configuration option "build.os": build not found added RTD to my list of OAuth applications and it has successfully cloned my repo -- it was failing previously -- however, a build now gives this errors:

```
Problem in your project's configuration. Invalid configuration option "build.os": build not found
```

Any advice gratefully received, thanks.

Cheers,
Norm.

**Comment by pradyunsg** [comment]
Please [synchronise your branch with the latest `main` branch](https://stackoverflow.com/questions/16329776/how-to-keep-a-branch-synchronized-updated-with-master).

**Comment by NormanDunbar** [comment]
Hi @pradyunsg and thanks for your advice. I am building with the "master" branch as this is a documentation repo. My branch is up to date. Unfortunately, this isn't the cause of my current problem.

Cheers,
Norm.

**Comment by NormanDunbar** [comment]
Ok, I think I've "fixed" it now! In case anyone is still having build problems, here's what I ended up having to do:

1. Update `.readthedocs.yaml`, in the root of my repository, to the following:

```
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - python -m pip install sphinx_rtd_theme

# Build documentation with Sphinx.
sphinx:
  builder: html
  configuration: sphinx/source/conf.py
  fail_on_warning: false

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
# python:
#   install:
#   -
```
I had to add the `build` details, which does match up with the error message I was seeing.

The `jobs` detail was also necessary as it seems that the sphinx_rtd_theme isn't installed automagically as part of the build now/any more. This bit was required:

```
jobs:
    post_create_environment:
      - python -m pip install sphinx_rtd_theme
```

2. Update `sphinx/source/conf.py`  (in my case) and add:
```
extensions = ['sphinx_rtd_theme']
```

I already had it in as the `html_template` but it seems that's no longer all that is required.

Thanks for the help.

Cheers,
Norm.
